name: Android CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout TouchController
        uses: actions/checkout@v3
        with:
          repository: fifth-light/TouchController
          path: TouchController

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build TouchController
        run: '(cd TouchController && chmod u+x gradlew && ./gradlew proxy-server:publishToMavenLocal proxy-client:publishToMavenLocal)'

      - name: Set IS_OFFICIAL if in the Creator Repository
        if: github.repository_owner == 'Vera-Firefly'
        run: echo "IS_OFFICIAL=true" >> $GITHUB_ENV

      - name: Get Jre
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: jrepush.yml
          path: app_pojavlauncher/src/main/assets/components
          workflow_conclusion: success
          repo: Vera-Firefly/android-openjdk-autobuild
          branch: main
          name: jre-pojav

      - name: Get JSPH
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: jrepush.yml
          path: app_pojavlauncher/src/main/jniLibs/arm64-v8a
          workflow_conclusion: success
          repo: Vera-Firefly/android-openjdk-autobuild
          branch: main
          name: libjsph

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19

      - name: Build Release ${{matrix.arch}} .apk
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main_v3'
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assemblerelease -Darch=${{matrix.arch}}

      - name: Build Debug ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Release
        if: github.repository_owner == 'Vera-Firefly' && github.ref_name == 'main_v3'
        uses: actions/upload-artifact@v4
        with:
          name: PGW-release-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/release/*

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: PGW-debug-${{matrix.arch}}
          path: app_pojavlauncher/build/outputs/apk/debug/*

  buildnoruntime:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [ "all", "arm", "arm64", "x86", "x86_64" ]
      fail-fast: false

    env:
      CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
      VERA_KEYSTORE_PASSWORD: ${{ secrets.VERA_KEYSTORE_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout TouchController
        uses: actions/checkout@v3
        with:
          repository: fifth-light/TouchController
          path: TouchController

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build TouchController
        run: '(cd TouchController && chmod u+x gradlew && ./gradlew proxy-server:publishToMavenLocal proxy-client:publishToMavenLocal)'

      - name: Set IS_OFFICIAL if in the Creator Repository
        if: github.repository_owner == 'Vera-Firefly'
        run: echo "IS_OFFICIAL=true" >> $GITHUB_ENV

      - name: Get JSPH
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: jrepush.yml
          path: app_pojavlauncher/src/main/jniLibs/arm64-v8a
          workflow_conclusion: success
          repo: Vera-Firefly/android-openjdk-autobuild
          branch: main
          name: libjsph

      - name: Get LWJGL3
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: main.yml
          path: app_pojavlauncher/src/main/assets/components/lwjgl3
          workflow_conclusion: success
          repo: Vera-Firefly/lwjgl3-build
          branch: main
          name: lwjgl

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19

      - name: Build Debug-noruntime ${{matrix.arch}} .apk
        run: |
          chmod +x gradlew
          ./gradlew app_pojavlauncher:assembleDebug -Darch=${{matrix.arch}}

      - name: Upload Debug
        uses: actions/upload-artifact@v4
        with:
          name: PGW-debug-${{matrix.arch}}-noruntime
          path: app_pojavlauncher/build/outputs/apk/debug/*
